name: Read EUR Exchange Rate from VIB

on:
  workflow_dispatch:

permissions:
  contents: write    

jobs:
  read_eur_from_vib:
    runs-on: windows-2022

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: data   # checkout directly to data branch     

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install selenium webdriver-manager beautifulsoup4

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Get-VIBRate
        run: python Get-VIBRate.py

      - name: Push updated result.json to data branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add result.json
          git commit -m "Update result.json from workflow" || echo "No changes to commit"
          git push origin data  